sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
#  - "pypy3" # Disable pypy3 until Travis updates it to >= 3.3
install:
  - pip install -vr requirements.txt
  - make install
script:
  - make check
notifications:
  irc: "irc.freenode.org##fonts"
  email: fonttools@googlegroups.com
