environment:

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      TOXENV: "py27-cov,py27-cov-lxml"
      TOXPYTHON: "C:\\Python27\\python.exe"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      TOXENV: "py36-cov,py36-cov-lxml"
      TOXPYTHON: "C:\\Python36-x64\\python.exe"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      # lxml doesn't have windows 3.7 wheels yet
      # TOXENV: "py37-cov,py37-cov-lxml"
      TOXENV: "py37-cov"
      TOXPYTHON: "C:\\Python37-x64\\python.exe"

skip_branch_with_pr: true

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  # install Python and pip when not already installed
  - ps: (new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/pypa/python-packaging-user-guide/49bf76f/source/code/install.ps1', 'install.ps1')
  - ps: if (-not(Test-Path($env:PYTHON))) { & install.ps1 }

  # prepend newly installed Python to the PATH
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # upgrade pip to avoid out-of-date warnings
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"

  # install/upgrade setuptools and wheel to build packages
  - "pip install --upgrade setuptools wheel"

  # install tox to run test suite in a virtual environment
  - "pip install -U tox"

build: false

test_script:
  - "tox"

on_success:
  # upload test coverage to codecov.io
  - tox -e codecov
